language: java
jdk:
  - openjdk8
services:
  - mysql
#sonar qube
addons:
  sonarcloud:
    organization: "dusanbucan"
jobs:
  include:
    # da izdelim na master granu i testne grane
    # pa da pokrecem razlicite baze u zavisnosti
    # od toga da li je test ili je master??
    - 
      if: (type = push AND branch = master) OR (type = push AND branch = testSector)
      before_script:
        # - mysql -u root -e 'CREATE DATABASE events_database;'
        - mysql -u root -e "CREATE USER 'events'@'localhost' IDENTIFIED BY 'events1!';"
        # - mysql -u root -e "GRANT ALL ON events_database.* TO 'events'@'localhost';"

        # da li moze ovako sa 2 baze??? ---> msm posto su obe na istom portu.
        - mysql -u root -e 'CREATE DATABASE test;'
        - mysql -u root -e "GRANT ALL ON test.* TO 'events'@'localhost';"
      install:
        - cd ./events 
        # -DskipTests=false --> da li je ovo da preskoci dependancije iz pom.xml-a 
        # ako su ozancene sa scope da su prisutne smao u test-u...
        - mvn install -Dmaven.javadoc.skip=true -B -V
      script:  
        #########
        # ovo samo ako hoces da izblidas i da pokrenes app
        # - mvn compile  # iskompajlira app i stavi .jar u traget folder
        # - java -jar target/events-0.0.1-SNAPSHOT.jar
        # - curl -I http://localhost:8080
        ########
      
        ########
        # dodat sonar qube
        - mvn clean verify sonar:sonar -Pcoverage -Dsonar.projectKey=DusanBucan_Events
        ########



